### ISSUE TITLE
Suggestions: Adding support for sparse matrices

### ISSUE THREAD

**Issue by nadavkun** [conroylau/lpinfer#106]
Hi, 
As some of the methods in the package are used for inference of large-scale linear programming problem I think it would be useful to allow the lpmodel function to accept sparse matrices 

Nadav

**Comment by nadavkun** [comment]
Hi Conroy,
I haven't had the time to check the new improvements, but just wanted to point out that in the FSST function there some cases in which you use as.matrix() function on the lpm model matrices, which turn them back into non-sparse matrices. I don't know if you changed them as well, but if not, I think it's worthwhile to do this as well. 

Best,
Nadav

**Comment by conroylau** [comment]
Hi Nadav,

Thanks for your feedback. It is handled, except for a few places when we pass the matrices to some `model` objects in the `gurobi` function. For example, `model$obj` cannot be a `sparseMatrix`, so I coerce it as a matrix there.
