### ISSUE TITLE
Missing Documentation(?)

### ISSUE THREAD

**Issue by nadavkun** [conroylau/lpinfer#107]
Hi,
I might be wrong, but I wasn't able to find documentation on the following:
- What does the "missing-data" problem in FSST documentation is 
- What are and how the logical bounds that the FSST function returns, are defined 

Nadav

**Comment by conroylau** [comment]
Hi Nadav, 

Thanks for your questions!

- The missing data problem is one of the examples that is used to demonstrate how our package can be used, not just the FSST method. A brief description of this example can be found in `/inst/example/dgp_missingdata.R`.
- Similarly, the logical bounds are computed for all the statistical inference methods in our package, not just FSST. You may find the documentation in `check.betatgt` and `check.betatgt.lp`. For your reference, the logical bounds are used to check whether the test point `beta.tgt` is logically possible. The upper and lower bounds are obtained by solving the following linear programs:
min/max A_tgt x
subject to
A_shp x = beta_shp
x >= 0

**Comment by conroylau** [comment]
Hi Nadav, 

Thanks for your questions!

- The missing data problem is one of the examples that is used to demonstrate how our package can be used, not just the FSST method. A brief description of this example can be found in `/inst/example/dgp_missingdata.R`.
- Similarly, the logical bounds are computed for all the statistical inference methods in our package, not just FSST. You may find the documentation in `check.betatgt` and `check.betatgt.lp`. For your reference, the logical bounds are used to check whether the test point `beta.tgt` is logically possible. The upper and lower bounds are obtained by solving the following linear programs:
min/max A.tgt x
subject to
A.shp x = beta.shp
x >= 0

**Comment by nadavkun** [comment]
Thanks!
