### ISSUE TITLE
A (possible) error in calculating p-value in FSST

### ISSUE THREAD

**Issue by szhuang1** [conroylau/lpinfer#111]
In the `fsst.pval` function, the p-value after obtaining `T.n` and a list of `T.bs` is calculated as 
```{r}
pval <- mean(T.bs > T.n)
```
Consider the case where `T.n = 0` so the null should not be rejected nomatter what `T.bs` is, since the test is given by
\phi_n := 1{T_n > \hat{c}_n (1-\alpha)}
However, depending on what `T.bs` actually are, `pval` may or may not be above a pre-specified `alpha`. The most extreme case is that if all of `T.bs` and `T.n` are 0, which can happen if we are "so far in the interior of the null that the "drift" we are plugging into the bootstrap is very negative. Then the solution is to solve the linear program by plugging in zero" as said by Andres. But now `pval` = 0 and we are always rejecting the null.
A correction proposed by Yuehao is to write
```{r}
pval <- mean(T.bs >= T.n)
```

**Comment by conroylau** [comment]
Sorry for the late reply. The procedure has been updated. Thanks for reporting this!
